// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"SpaceTraders/pkg/models/shared"
	"net/http"
)

type AcceptContractSecurity struct {
	AgentToken string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

type AcceptContractRequest struct {
	ContractID string `pathParam:"style=simple,explode=false,name=contractId"`
}

type AcceptContract200ApplicationJSONData struct {
	Agent    shared.Agent    `json:"agent"`
	Contract shared.Contract `json:"contract"`
}

// AcceptContract200ApplicationJSON - OK
type AcceptContract200ApplicationJSON struct {
	Data AcceptContract200ApplicationJSONData `json:"data"`
}

type AcceptContractResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	AcceptContract200ApplicationJSONObject *AcceptContract200ApplicationJSON
}
