// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"SpaceTraders/pkg/models/shared"
	"net/http"
)

type CreateChartSecurity struct {
	AgentToken string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

type CreateChartRequest struct {
	// The symbol of the ship
	ShipSymbol string `pathParam:"style=simple,explode=false,name=shipSymbol"`
}

type CreateChart201ApplicationJSONData struct {
	// The chart of a system or waypoint, which makes the location visible to other agents.
	Chart shared.Chart `json:"chart"`
	// A waypoint is a location that ships can travel to such as a Planet, Moon or Space Station.
	Waypoint shared.Waypoint `json:"waypoint"`
}

// CreateChart201ApplicationJSON - Created
type CreateChart201ApplicationJSON struct {
	Data CreateChart201ApplicationJSONData `json:"data"`
}

type CreateChartResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Created
	CreateChart201ApplicationJSONObject *CreateChart201ApplicationJSON
}
