// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"SpaceTraders/pkg/models/shared"
	"net/http"
)

type CreateShipWaypointScanSecurity struct {
	AgentToken string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

type CreateShipWaypointScanRequest struct {
	ShipSymbol string `pathParam:"style=simple,explode=false,name=shipSymbol"`
}

type CreateShipWaypointScan201ApplicationJSONData struct {
	// A cooldown is a period of time in which a ship cannot perform certain actions.
	Cooldown  shared.Cooldown          `json:"cooldown"`
	Waypoints []shared.ScannedWaypoint `json:"waypoints"`
}

// CreateShipWaypointScan201ApplicationJSON - Created
type CreateShipWaypointScan201ApplicationJSON struct {
	Data CreateShipWaypointScan201ApplicationJSONData `json:"data"`
}

type CreateShipWaypointScanResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Created
	CreateShipWaypointScan201ApplicationJSONObject *CreateShipWaypointScan201ApplicationJSON
}
