// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"SpaceTraders/pkg/models/shared"
	"net/http"
)

type CreateShipSystemScanSecurity struct {
	AgentToken string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

type CreateShipSystemScanRequest struct {
	ShipSymbol string `pathParam:"style=simple,explode=false,name=shipSymbol"`
}

type CreateShipSystemScan201ApplicationJSONData struct {
	// A cooldown is a period of time in which a ship cannot perform certain actions.
	Cooldown shared.Cooldown        `json:"cooldown"`
	Systems  []shared.ScannedSystem `json:"systems"`
}

// CreateShipSystemScan201ApplicationJSON - Created
type CreateShipSystemScan201ApplicationJSON struct {
	Data CreateShipSystemScan201ApplicationJSONData `json:"data"`
}

type CreateShipSystemScanResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Created
	CreateShipSystemScan201ApplicationJSONObject *CreateShipSystemScan201ApplicationJSON
}
