// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"SpaceTraders/pkg/models/shared"
	"net/http"
)

type CreateShipShipScanSecurity struct {
	AgentToken string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

type CreateShipShipScanRequest struct {
	ShipSymbol string `pathParam:"style=simple,explode=false,name=shipSymbol"`
}

type CreateShipShipScan201ApplicationJSONData struct {
	// A cooldown is a period of time in which a ship cannot perform certain actions.
	Cooldown shared.Cooldown      `json:"cooldown"`
	Ships    []shared.ScannedShip `json:"ships"`
}

// CreateShipShipScan201ApplicationJSON - Created
type CreateShipShipScan201ApplicationJSON struct {
	Data CreateShipShipScan201ApplicationJSONData `json:"data"`
}

type CreateShipShipScanResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Created
	CreateShipShipScan201ApplicationJSONObject *CreateShipShipScan201ApplicationJSON
}
