// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"SpaceTraders/pkg/models/shared"
	"net/http"
)

type DockShipSecurity struct {
	AgentToken string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

type DockShipRequest struct {
	// The symbol of the ship
	ShipSymbol string `pathParam:"style=simple,explode=false,name=shipSymbol"`
}

type DockShipDockShip200ResponseData struct {
	// The navigation information of the ship.
	Nav shared.ShipNav `json:"nav"`
}

// DockShipDockShip200Response - The ship has successfully docked at it's current location.
type DockShipDockShip200Response struct {
	Data DockShipDockShip200ResponseData `json:"data"`
}

type DockShipResponse struct {
	ContentType string
	// The ship has successfully docked at it's current location.
	DockShip200Response *DockShipDockShip200Response
	StatusCode          int
	RawResponse         *http.Response
}
