// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"SpaceTraders/pkg/models/shared"
	"net/http"
)

type ExtractResourcesSecurity struct {
	AgentToken string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

type ExtractResourcesRequestBody struct {
	// A resource survey of a waypoint, detailing a specific extraction location and the types of resources that can be found there.
	Survey *shared.Survey `json:"survey,omitempty"`
}

type ExtractResourcesRequest struct {
	RequestBody *ExtractResourcesRequestBody `request:"mediaType=application/json"`
	// The ship symbol
	ShipSymbol string `pathParam:"style=simple,explode=false,name=shipSymbol"`
}

type ExtractResources201ApplicationJSONData struct {
	Cargo shared.ShipCargo `json:"cargo"`
	// A cooldown is a period of time in which a ship cannot perform certain actions.
	Cooldown   shared.Cooldown   `json:"cooldown"`
	Extraction shared.Extraction `json:"extraction"`
}

// ExtractResources201ApplicationJSON - Created
type ExtractResources201ApplicationJSON struct {
	Data ExtractResources201ApplicationJSONData `json:"data"`
}

type ExtractResourcesResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Created
	ExtractResources201ApplicationJSONObject *ExtractResources201ApplicationJSON
}
