// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"SpaceTraders/pkg/models/shared"
	"net/http"
)

type FulfillContractSecurity struct {
	AgentToken string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

type FulfillContractRequest struct {
	// The ID of the contract
	ContractID string `pathParam:"style=simple,explode=false,name=contractId"`
}

type FulfillContract200ApplicationJSONData struct {
	Agent    shared.Agent    `json:"agent"`
	Contract shared.Contract `json:"contract"`
}

// FulfillContract200ApplicationJSON - OK
type FulfillContract200ApplicationJSON struct {
	Data FulfillContract200ApplicationJSONData `json:"data"`
}

type FulfillContractResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	FulfillContract200ApplicationJSONObject *FulfillContract200ApplicationJSON
}
