// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"SpaceTraders/pkg/models/shared"
	"net/http"
)

type GetContractSecurity struct {
	AgentToken string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

type GetContractRequest struct {
	// The contract ID
	ContractID string `pathParam:"style=simple,explode=false,name=contractId"`
}

// GetContract200ApplicationJSON - OK
type GetContract200ApplicationJSON struct {
	Data shared.Contract `json:"data"`
}

type GetContractResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	GetContract200ApplicationJSONObject *GetContract200ApplicationJSON
}
