// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"SpaceTraders/pkg/models/shared"
	"net/http"
)

type GetContractsSecurity struct {
	AgentToken string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

type GetContractsRequest struct {
	// How many entries to return per page
	Limit *int64 `queryParam:"style=form,explode=true,name=limit"`
	// What entry offset to request
	Page *int64 `queryParam:"style=form,explode=true,name=page"`
}

// GetContracts200ApplicationJSON - OK
type GetContracts200ApplicationJSON struct {
	Data []shared.Contract `json:"data"`
	Meta shared.Meta       `json:"meta"`
}

type GetContractsResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	GetContracts200ApplicationJSONObject *GetContracts200ApplicationJSON
}
