// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"SpaceTraders/pkg/models/shared"
	"net/http"
)

type GetFactionRequest struct {
	// The faction symbol
	FactionSymbol string `pathParam:"style=simple,explode=false,name=factionSymbol"`
}

// GetFaction200ApplicationJSON - OK
type GetFaction200ApplicationJSON struct {
	Data shared.Faction `json:"data"`
}

type GetFactionResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	GetFaction200ApplicationJSONObject *GetFaction200ApplicationJSON
}
