// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"SpaceTraders/pkg/models/shared"
	"net/http"
)

type GetFactionsRequest struct {
	// How many entries to return per page
	Limit *int64 `queryParam:"style=form,explode=true,name=limit"`
	// What entry offset to request
	Page *int64 `queryParam:"style=form,explode=true,name=page"`
}

type GetFactions200ApplicationJSON struct {
	Data []shared.Faction `json:"data"`
	Meta shared.Meta      `json:"meta"`
}

type GetFactionsResponse struct {
	ContentType                         string
	StatusCode                          int
	RawResponse                         *http.Response
	GetFactions200ApplicationJSONObject *GetFactions200ApplicationJSON
}
