// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"SpaceTraders/pkg/models/shared"
	"net/http"
)

type GetMyAgentSecurity struct {
	AgentToken string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

// GetMyAgent200ApplicationJSON - OK
type GetMyAgent200ApplicationJSON struct {
	Data shared.Agent `json:"data"`
}

type GetMyAgentResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	GetMyAgent200ApplicationJSONObject *GetMyAgent200ApplicationJSON
}
