// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"SpaceTraders/pkg/models/shared"
	"net/http"
)

type GetMyShipSecurity struct {
	AgentToken string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

type GetMyShipRequest struct {
	ShipSymbol string `pathParam:"style=simple,explode=false,name=shipSymbol"`
}

// GetMyShip200ApplicationJSON - OK
type GetMyShip200ApplicationJSON struct {
	// A ship
	Data shared.Ship `json:"data"`
}

type GetMyShipResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	GetMyShip200ApplicationJSONObject *GetMyShip200ApplicationJSON
}
