// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"SpaceTraders/pkg/models/shared"
	"net/http"
)

type GetMarketRequest struct {
	// The system symbol
	SystemSymbol string `pathParam:"style=simple,explode=false,name=systemSymbol"`
	// The waypoint symbol
	WaypointSymbol string `pathParam:"style=simple,explode=false,name=waypointSymbol"`
}

// GetMarket200ApplicationJSON - OK
type GetMarket200ApplicationJSON struct {
	Data shared.Market `json:"data"`
}

type GetMarketResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	GetMarket200ApplicationJSONObject *GetMarket200ApplicationJSON
}
