// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"SpaceTraders/pkg/models/shared"
	"net/http"
)

type GetMyShipCargoSecurity struct {
	AgentToken string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

type GetMyShipCargoRequest struct {
	// The symbol of the ship
	ShipSymbol string `pathParam:"style=simple,explode=false,name=shipSymbol"`
}

// GetMyShipCargo200ApplicationJSON - OK
type GetMyShipCargo200ApplicationJSON struct {
	Data shared.ShipCargo `json:"data"`
}

type GetMyShipCargoResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	GetMyShipCargo200ApplicationJSONObject *GetMyShipCargo200ApplicationJSON
}
