// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"SpaceTraders/pkg/models/shared"
	"net/http"
)

type GetShipCooldownSecurity struct {
	AgentToken string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

type GetShipCooldownRequest struct {
	ShipSymbol string `pathParam:"style=simple,explode=false,name=shipSymbol"`
}

// GetShipCooldown200ApplicationJSON - OK
type GetShipCooldown200ApplicationJSON struct {
	// A cooldown is a period of time in which a ship cannot perform certain actions.
	Data shared.Cooldown `json:"data"`
}

type GetShipCooldownResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	GetShipCooldown200ApplicationJSONObject *GetShipCooldown200ApplicationJSON
}
