// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"SpaceTraders/pkg/models/shared"
	"net/http"
)

type GetSystemWaypointsSecurity struct {
	AgentToken string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

type GetSystemWaypointsRequest struct {
	// How many entries to return per page
	Limit *int64 `queryParam:"style=form,explode=true,name=limit"`
	// What entry offset to request
	Page *int64 `queryParam:"style=form,explode=true,name=page"`
	// The system symbol
	SystemSymbol string `pathParam:"style=simple,explode=false,name=systemSymbol"`
}

// GetSystemWaypoints200ApplicationJSON - OK
type GetSystemWaypoints200ApplicationJSON struct {
	Data []shared.Waypoint `json:"data"`
	Meta shared.Meta       `json:"meta"`
}

type GetSystemWaypointsResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	GetSystemWaypoints200ApplicationJSONObject *GetSystemWaypoints200ApplicationJSON
}
