// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"SpaceTraders/pkg/models/shared"
	"net/http"
)

type GetSystemsRequest struct {
	// How many entries to return per page
	Limit *int64 `queryParam:"style=form,explode=true,name=limit"`
	// What entry offset to request
	Page *int64 `queryParam:"style=form,explode=true,name=page"`
}

// GetSystems200ApplicationJSON - OK
type GetSystems200ApplicationJSON struct {
	Data []shared.System `json:"data"`
	Meta shared.Meta     `json:"meta"`
}

type GetSystemsResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	GetSystems200ApplicationJSONObject *GetSystems200ApplicationJSON
}
