// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"SpaceTraders/pkg/models/shared"
	"net/http"
)

type GetShipNavSecurity struct {
	AgentToken string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

type GetShipNavRequest struct {
	// The ship symbol
	ShipSymbol string `pathParam:"style=simple,explode=false,name=shipSymbol"`
}

// GetShipNav200ApplicationJSON - The current nav status of the ship.
type GetShipNav200ApplicationJSON struct {
	// The navigation information of the ship.
	Data shared.ShipNav `json:"data"`
}

type GetShipNavResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// The current nav status of the ship.
	GetShipNav200ApplicationJSONObject *GetShipNav200ApplicationJSON
}
