// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"SpaceTraders/pkg/models/shared"
	"net/http"
)

type GetSystemRequest struct {
	// The system symbol
	SystemSymbol string `pathParam:"style=simple,explode=false,name=systemSymbol"`
}

// GetSystem200ApplicationJSON - OK
type GetSystem200ApplicationJSON struct {
	Data shared.System `json:"data"`
}

type GetSystemResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	GetSystem200ApplicationJSONObject *GetSystem200ApplicationJSON
}
