// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"SpaceTraders/pkg/models/shared"
	"net/http"
)

type GetShipyardRequest struct {
	// The system symbol
	SystemSymbol string `pathParam:"style=simple,explode=false,name=systemSymbol"`
	// The waypoint symbol
	WaypointSymbol string `pathParam:"style=simple,explode=false,name=waypointSymbol"`
}

// GetShipyard200ApplicationJSON - OK
type GetShipyard200ApplicationJSON struct {
	Data shared.Shipyard `json:"data"`
}

type GetShipyardResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	GetShipyard200ApplicationJSONObject *GetShipyard200ApplicationJSON
}
