// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"SpaceTraders/pkg/models/shared"
	"net/http"
)

type GetWaypointRequest struct {
	// The system symbol
	SystemSymbol string `pathParam:"style=simple,explode=false,name=systemSymbol"`
	// The waypoint symbol
	WaypointSymbol string `pathParam:"style=simple,explode=false,name=waypointSymbol"`
}

// GetWaypoint200ApplicationJSON - OK
type GetWaypoint200ApplicationJSON struct {
	// A waypoint is a location that ships can travel to such as a Planet, Moon or Space Station.
	Data shared.Waypoint `json:"data"`
}

type GetWaypointResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	GetWaypoint200ApplicationJSONObject *GetWaypoint200ApplicationJSON
}
