// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"SpaceTraders/pkg/models/shared"
	"net/http"
)

type JettisonSecurity struct {
	AgentToken string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

type JettisonRequestBody struct {
	Symbol string `json:"symbol"`
	Units  int64  `json:"units"`
}

type JettisonRequest struct {
	RequestBody *JettisonRequestBody `request:"mediaType=application/json"`
	ShipSymbol  string               `pathParam:"style=simple,explode=false,name=shipSymbol"`
}

type Jettison200ApplicationJSONData struct {
	Cargo shared.ShipCargo `json:"cargo"`
}

// Jettison200ApplicationJSON - OK
type Jettison200ApplicationJSON struct {
	Data Jettison200ApplicationJSONData `json:"data"`
}

type JettisonResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	Jettison200ApplicationJSONObject *Jettison200ApplicationJSON
}
