// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"SpaceTraders/pkg/models/shared"
	"net/http"
)

type JumpShipSecurity struct {
	AgentToken string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

type JumpShipRequestBody struct {
	// The system symbol to jump to.
	SystemSymbol string `json:"systemSymbol"`
}

type JumpShipRequest struct {
	RequestBody *JumpShipRequestBody `request:"mediaType=application/json"`
	ShipSymbol  string               `pathParam:"style=simple,explode=false,name=shipSymbol"`
}

type JumpShip200ApplicationJSONData struct {
	// A cooldown is a period of time in which a ship cannot perform certain actions.
	Cooldown shared.Cooldown `json:"cooldown"`
	// The navigation information of the ship.
	Nav *shared.ShipNav `json:"nav,omitempty"`
}

// JumpShip200ApplicationJSON - OK
type JumpShip200ApplicationJSON struct {
	Data JumpShip200ApplicationJSONData `json:"data"`
}

type JumpShipResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	JumpShip200ApplicationJSONObject *JumpShip200ApplicationJSON
}
