// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"SpaceTraders/pkg/models/shared"
	"net/http"
)

type NegotiateContractSecurity struct {
	AgentToken string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

type NegotiateContractRequest struct {
	RequestBody interface{} `request:"mediaType=application/json"`
	ShipSymbol  string      `pathParam:"style=simple,explode=false,name=shipSymbol"`
}

type NegotiateContractNegotiateContract200ResponseData struct {
	Contract shared.Contract `json:"contract"`
}

// NegotiateContractNegotiateContract200Response - Created
type NegotiateContractNegotiateContract200Response struct {
	Data NegotiateContractNegotiateContract200ResponseData `json:"data"`
}

type NegotiateContractResponse struct {
	ContentType string
	// Created
	NegotiateContract200Response *NegotiateContractNegotiateContract200Response
	StatusCode                   int
	RawResponse                  *http.Response
}
