// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"SpaceTraders/pkg/models/shared"
	"net/http"
)

type OrbitShipSecurity struct {
	AgentToken string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

type OrbitShipRequest struct {
	// The symbol of the ship
	ShipSymbol string `pathParam:"style=simple,explode=false,name=shipSymbol"`
}

type OrbitShipOrbitShip200ResponseData struct {
	// The navigation information of the ship.
	Nav shared.ShipNav `json:"nav"`
}

// OrbitShipOrbitShip200Response - The ship has successfully moved into orbit at it's current location.
type OrbitShipOrbitShip200Response struct {
	Data OrbitShipOrbitShip200ResponseData `json:"data"`
}

type OrbitShipResponse struct {
	ContentType string
	// The ship has successfully moved into orbit at it's current location.
	OrbitShip200Response *OrbitShipOrbitShip200Response
	StatusCode           int
	RawResponse          *http.Response
}
