// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"SpaceTraders/pkg/models/shared"
	"net/http"
)

type PatchShipNavSecurity struct {
	AgentToken string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

type PatchShipNavRequestBody struct {
	// The ship's set speed when traveling between waypoints or systems.
	FlightMode *shared.ShipNavFlightMode `json:"flightMode,omitempty"`
}

type PatchShipNavRequest struct {
	RequestBody *PatchShipNavRequestBody `request:"mediaType=application/json"`
	// The ship symbol
	ShipSymbol string `pathParam:"style=simple,explode=false,name=shipSymbol"`
}

// PatchShipNav200ApplicationJSON - The updated nav status of the ship.
type PatchShipNav200ApplicationJSON struct {
	// The navigation information of the ship.
	Data shared.ShipNav `json:"data"`
}

type PatchShipNavResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// The updated nav status of the ship.
	PatchShipNav200ApplicationJSONObject *PatchShipNav200ApplicationJSON
}
