// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"SpaceTraders/pkg/models/shared"
	"net/http"
)

type PurchaseShipSecurity struct {
	AgentToken string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

type PurchaseShipRequestBody struct {
	ShipType shared.ShipType `json:"shipType"`
	// The symbol of the waypoint you want to purchase the ship at.
	WaypointSymbol string `json:"waypointSymbol"`
}

type PurchaseShip201ApplicationJSONData struct {
	Agent shared.Agent `json:"agent"`
	// A ship
	Ship        shared.Ship                `json:"ship"`
	Transaction shared.ShipyardTransaction `json:"transaction"`
}

// PurchaseShip201ApplicationJSON - Created
type PurchaseShip201ApplicationJSON struct {
	Data PurchaseShip201ApplicationJSONData `json:"data"`
}

type PurchaseShipResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Created
	PurchaseShip201ApplicationJSONObject *PurchaseShip201ApplicationJSON
}
