// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"SpaceTraders/pkg/models/shared"
	"net/http"
)

type RefuelShipSecurity struct {
	AgentToken string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

type RefuelShipRequest struct {
	ShipSymbol string `pathParam:"style=simple,explode=false,name=shipSymbol"`
}

type RefuelShip200ApplicationJSONData struct {
	Agent shared.Agent `json:"agent"`
	// Details of the ship's fuel tanks including how much fuel was consumed during the last transit or action.
	Fuel        shared.ShipFuel          `json:"fuel"`
	Transaction shared.MarketTransaction `json:"transaction"`
}

// RefuelShip200ApplicationJSON - OK
type RefuelShip200ApplicationJSON struct {
	Data RefuelShip200ApplicationJSONData `json:"data"`
}

type RefuelShipResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	RefuelShip200ApplicationJSONObject *RefuelShip200ApplicationJSON
}
