// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"SpaceTraders/pkg/models/shared"
	"net/http"
)

type TransferCargoSecurity struct {
	AgentToken string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

type TransferCargoTransferCargoRequest struct {
	ShipSymbol  string `json:"shipSymbol"`
	TradeSymbol string `json:"tradeSymbol"`
	Units       int64  `json:"units"`
}

type TransferCargoRequest struct {
	RequestBody *TransferCargoTransferCargoRequest `request:"mediaType=application/json"`
	ShipSymbol  string                             `pathParam:"style=simple,explode=false,name=shipSymbol"`
}

type TransferCargoTransferCargo200ResponseData struct {
	Cargo shared.ShipCargo `json:"cargo"`
}

// TransferCargoTransferCargo200Response - Created
type TransferCargoTransferCargo200Response struct {
	Data TransferCargoTransferCargo200ResponseData `json:"data"`
}

type TransferCargoResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Created
	TransferCargo200Response *TransferCargoTransferCargo200Response
}
