// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"SpaceTraders/pkg/models/shared"
	"net/http"
)

type WarpShipSecurity struct {
	AgentToken string `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

type WarpShipRequestBody struct {
	// The target destination.
	WaypointSymbol string `json:"waypointSymbol"`
}

type WarpShipRequest struct {
	RequestBody *WarpShipRequestBody `request:"mediaType=application/json"`
	ShipSymbol  string               `pathParam:"style=simple,explode=false,name=shipSymbol"`
}

type WarpShip200ApplicationJSONData struct {
	// Details of the ship's fuel tanks including how much fuel was consumed during the last transit or action.
	Fuel shared.ShipFuel `json:"fuel"`
	// The navigation information of the ship.
	Nav shared.ShipNav `json:"nav"`
}

// WarpShip200ApplicationJSON - The successful transit information including the route details and changes to ship fuel, supplies, and crew wages paid. The route includes the expected time of arrival.
type WarpShip200ApplicationJSON struct {
	Data WarpShip200ApplicationJSONData `json:"data"`
}

type WarpShipResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// The successful transit information including the route details and changes to ship fuel, supplies, and crew wages paid. The route includes the expected time of arrival.
	WarpShip200ApplicationJSONObject *WarpShip200ApplicationJSON
}
