// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Agent struct {
	AccountID string `json:"accountId"`
	// The number of credits the agent has available. Credits can be negative if funds have been overdrawn.
	Credits int64 `json:"credits"`
	// The headquarters of the agent.
	Headquarters string `json:"headquarters"`
	// The faction the agent started with.
	StartingFaction string `json:"startingFaction"`
	Symbol          string `json:"symbol"`
}
