// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

// Chart - The chart of a system or waypoint, which makes the location visible to other agents.
type Chart struct {
	SubmittedBy    *string    `json:"submittedBy,omitempty"`
	SubmittedOn    *time.Time `json:"submittedOn,omitempty"`
	WaypointSymbol *string    `json:"waypointSymbol,omitempty"`
}
