// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ConnectedSystem struct {
	Distance int64 `json:"distance"`
	// The symbol of the faction that owns the connected jump gate in the system.
	FactionSymbol *string `json:"factionSymbol,omitempty"`
	SectorSymbol  string  `json:"sectorSymbol"`
	Symbol        string  `json:"symbol"`
	// The type of waypoint.
	Type SystemType `json:"type"`
	X    int64      `json:"x"`
	Y    int64      `json:"y"`
}
