// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

type ContractTerms struct {
	// The deadline for the contract.
	Deadline time.Time             `json:"deadline"`
	Deliver  []ContractDeliverGood `json:"deliver,omitempty"`
	Payment  ContractPayment       `json:"payment"`
}
