// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ContractPayment struct {
	// The amount of credits received up front for accepting the contract.
	OnAccepted int64 `json:"onAccepted"`
	// The amount of credits received when the contract is fulfilled.
	OnFulfilled int64 `json:"onFulfilled"`
}
