// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

// Cooldown - A cooldown is a period of time in which a ship cannot perform certain actions.
type Cooldown struct {
	// The date and time when the cooldown expires in ISO 8601 format
	Expiration *time.Time `json:"expiration,omitempty"`
	// The remaining duration of the cooldown in seconds
	RemainingSeconds int64 `json:"remainingSeconds"`
	// The symbol of the ship that is on cooldown
	ShipSymbol string `json:"shipSymbol"`
	// The total duration of the cooldown in seconds
	TotalSeconds int64 `json:"totalSeconds"`
}
