// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Extraction struct {
	ShipSymbol string          `json:"shipSymbol"`
	Yield      ExtractionYield `json:"yield"`
}
