// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ExtractionYield struct {
	Symbol string `json:"symbol"`
	// The number of units extracted that were placed into the ship's cargo hold.
	Units int64 `json:"units"`
}
