// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Faction struct {
	Description  string `json:"description"`
	Headquarters string `json:"headquarters"`
	// Whether or not the faction is currently recruiting new agents.
	IsRecruiting bool           `json:"isRecruiting"`
	Name         string         `json:"name"`
	Symbol       string         `json:"symbol"`
	Traits       []FactionTrait `json:"traits"`
}
