// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// FactionTraitSymbol - The unique identifier of the trait.
type FactionTraitSymbol string

const (
	FactionTraitSymbolBureaucratic            FactionTraitSymbol = "BUREAUCRATIC"
	FactionTraitSymbolSecretive               FactionTraitSymbol = "SECRETIVE"
	FactionTraitSymbolCapitalistic            FactionTraitSymbol = "CAPITALISTIC"
	FactionTraitSymbolIndustrious             FactionTraitSymbol = "INDUSTRIOUS"
	FactionTraitSymbolPeaceful                FactionTraitSymbol = "PEACEFUL"
	FactionTraitSymbolDistrustful             FactionTraitSymbol = "DISTRUSTFUL"
	FactionTraitSymbolWelcoming               FactionTraitSymbol = "WELCOMING"
	FactionTraitSymbolSmugglers               FactionTraitSymbol = "SMUGGLERS"
	FactionTraitSymbolScavengers              FactionTraitSymbol = "SCAVENGERS"
	FactionTraitSymbolRebellious              FactionTraitSymbol = "REBELLIOUS"
	FactionTraitSymbolExiles                  FactionTraitSymbol = "EXILES"
	FactionTraitSymbolPirates                 FactionTraitSymbol = "PIRATES"
	FactionTraitSymbolRaiders                 FactionTraitSymbol = "RAIDERS"
	FactionTraitSymbolClan                    FactionTraitSymbol = "CLAN"
	FactionTraitSymbolGuild                   FactionTraitSymbol = "GUILD"
	FactionTraitSymbolDominion                FactionTraitSymbol = "DOMINION"
	FactionTraitSymbolFringe                  FactionTraitSymbol = "FRINGE"
	FactionTraitSymbolForsaken                FactionTraitSymbol = "FORSAKEN"
	FactionTraitSymbolIsolated                FactionTraitSymbol = "ISOLATED"
	FactionTraitSymbolLocalized               FactionTraitSymbol = "LOCALIZED"
	FactionTraitSymbolEstablished             FactionTraitSymbol = "ESTABLISHED"
	FactionTraitSymbolNotable                 FactionTraitSymbol = "NOTABLE"
	FactionTraitSymbolDominant                FactionTraitSymbol = "DOMINANT"
	FactionTraitSymbolInescapable             FactionTraitSymbol = "INESCAPABLE"
	FactionTraitSymbolInnovative              FactionTraitSymbol = "INNOVATIVE"
	FactionTraitSymbolBold                    FactionTraitSymbol = "BOLD"
	FactionTraitSymbolVisionary               FactionTraitSymbol = "VISIONARY"
	FactionTraitSymbolCurious                 FactionTraitSymbol = "CURIOUS"
	FactionTraitSymbolDaring                  FactionTraitSymbol = "DARING"
	FactionTraitSymbolExploratory             FactionTraitSymbol = "EXPLORATORY"
	FactionTraitSymbolResourceful             FactionTraitSymbol = "RESOURCEFUL"
	FactionTraitSymbolFlexible                FactionTraitSymbol = "FLEXIBLE"
	FactionTraitSymbolCooperative             FactionTraitSymbol = "COOPERATIVE"
	FactionTraitSymbolUnited                  FactionTraitSymbol = "UNITED"
	FactionTraitSymbolStrategic               FactionTraitSymbol = "STRATEGIC"
	FactionTraitSymbolIntelligent             FactionTraitSymbol = "INTELLIGENT"
	FactionTraitSymbolResearchFocused         FactionTraitSymbol = "RESEARCH_FOCUSED"
	FactionTraitSymbolCollaborative           FactionTraitSymbol = "COLLABORATIVE"
	FactionTraitSymbolProgressive             FactionTraitSymbol = "PROGRESSIVE"
	FactionTraitSymbolMilitaristic            FactionTraitSymbol = "MILITARISTIC"
	FactionTraitSymbolTechnologicallyAdvanced FactionTraitSymbol = "TECHNOLOGICALLY_ADVANCED"
	FactionTraitSymbolAggressive              FactionTraitSymbol = "AGGRESSIVE"
	FactionTraitSymbolImperialistic           FactionTraitSymbol = "IMPERIALISTIC"
	FactionTraitSymbolTreasureHunters         FactionTraitSymbol = "TREASURE_HUNTERS"
	FactionTraitSymbolDexterous               FactionTraitSymbol = "DEXTEROUS"
	FactionTraitSymbolUnpredictable           FactionTraitSymbol = "UNPREDICTABLE"
	FactionTraitSymbolBrutal                  FactionTraitSymbol = "BRUTAL"
	FactionTraitSymbolFleeting                FactionTraitSymbol = "FLEETING"
	FactionTraitSymbolAdaptable               FactionTraitSymbol = "ADAPTABLE"
	FactionTraitSymbolSelfSufficient          FactionTraitSymbol = "SELF_SUFFICIENT"
	FactionTraitSymbolDefensive               FactionTraitSymbol = "DEFENSIVE"
	FactionTraitSymbolProud                   FactionTraitSymbol = "PROUD"
	FactionTraitSymbolDiverse                 FactionTraitSymbol = "DIVERSE"
	FactionTraitSymbolIndependent             FactionTraitSymbol = "INDEPENDENT"
	FactionTraitSymbolSelfInterested          FactionTraitSymbol = "SELF_INTERESTED"
	FactionTraitSymbolFragmented              FactionTraitSymbol = "FRAGMENTED"
	FactionTraitSymbolCommercial              FactionTraitSymbol = "COMMERCIAL"
	FactionTraitSymbolFreeMarkets             FactionTraitSymbol = "FREE_MARKETS"
	FactionTraitSymbolEntrepreneurial         FactionTraitSymbol = "ENTREPRENEURIAL"
)

func (e FactionTraitSymbol) ToPointer() *FactionTraitSymbol {
	return &e
}

func (e *FactionTraitSymbol) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "BUREAUCRATIC":
		fallthrough
	case "SECRETIVE":
		fallthrough
	case "CAPITALISTIC":
		fallthrough
	case "INDUSTRIOUS":
		fallthrough
	case "PEACEFUL":
		fallthrough
	case "DISTRUSTFUL":
		fallthrough
	case "WELCOMING":
		fallthrough
	case "SMUGGLERS":
		fallthrough
	case "SCAVENGERS":
		fallthrough
	case "REBELLIOUS":
		fallthrough
	case "EXILES":
		fallthrough
	case "PIRATES":
		fallthrough
	case "RAIDERS":
		fallthrough
	case "CLAN":
		fallthrough
	case "GUILD":
		fallthrough
	case "DOMINION":
		fallthrough
	case "FRINGE":
		fallthrough
	case "FORSAKEN":
		fallthrough
	case "ISOLATED":
		fallthrough
	case "LOCALIZED":
		fallthrough
	case "ESTABLISHED":
		fallthrough
	case "NOTABLE":
		fallthrough
	case "DOMINANT":
		fallthrough
	case "INESCAPABLE":
		fallthrough
	case "INNOVATIVE":
		fallthrough
	case "BOLD":
		fallthrough
	case "VISIONARY":
		fallthrough
	case "CURIOUS":
		fallthrough
	case "DARING":
		fallthrough
	case "EXPLORATORY":
		fallthrough
	case "RESOURCEFUL":
		fallthrough
	case "FLEXIBLE":
		fallthrough
	case "COOPERATIVE":
		fallthrough
	case "UNITED":
		fallthrough
	case "STRATEGIC":
		fallthrough
	case "INTELLIGENT":
		fallthrough
	case "RESEARCH_FOCUSED":
		fallthrough
	case "COLLABORATIVE":
		fallthrough
	case "PROGRESSIVE":
		fallthrough
	case "MILITARISTIC":
		fallthrough
	case "TECHNOLOGICALLY_ADVANCED":
		fallthrough
	case "AGGRESSIVE":
		fallthrough
	case "IMPERIALISTIC":
		fallthrough
	case "TREASURE_HUNTERS":
		fallthrough
	case "DEXTEROUS":
		fallthrough
	case "UNPREDICTABLE":
		fallthrough
	case "BRUTAL":
		fallthrough
	case "FLEETING":
		fallthrough
	case "ADAPTABLE":
		fallthrough
	case "SELF_SUFFICIENT":
		fallthrough
	case "DEFENSIVE":
		fallthrough
	case "PROUD":
		fallthrough
	case "DIVERSE":
		fallthrough
	case "INDEPENDENT":
		fallthrough
	case "SELF_INTERESTED":
		fallthrough
	case "FRAGMENTED":
		fallthrough
	case "COMMERCIAL":
		fallthrough
	case "FREE_MARKETS":
		fallthrough
	case "ENTREPRENEURIAL":
		*e = FactionTraitSymbol(v)
		return nil
	default:
		return fmt.Errorf("invalid value for FactionTraitSymbol: %v", v)
	}
}

type FactionTrait struct {
	// A description of the trait.
	Description string `json:"description"`
	// The name of the trait.
	Name string `json:"name"`
	// The unique identifier of the trait.
	Symbol FactionTraitSymbol `json:"symbol"`
}
