// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type JumpGate struct {
	// The systems within range of the gate that have a corresponding gate.
	ConnectedSystems []ConnectedSystem `json:"connectedSystems"`
	// The symbol of the faction that owns the gate.
	FactionSymbol *string `json:"factionSymbol,omitempty"`
	// The maximum jump range of the gate.
	JumpRange float64 `json:"jumpRange"`
}
