// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Market struct {
	// The list of goods that are bought and sold between agents at this market.
	Exchange []TradeGood `json:"exchange"`
	// The list of goods that are exported from this market.
	Exports []TradeGood `json:"exports"`
	// The list of goods that are sought as imports in this market.
	Imports []TradeGood `json:"imports"`
	// The symbol of the market. The symbol is the same as the waypoint where the market is located.
	Symbol string `json:"symbol"`
	// The list of goods that are traded at this market. Visible only when a ship is present at the market.
	TradeGoods []MarketTradeGood `json:"tradeGoods,omitempty"`
	// The list of recent transactions at this market. Visible only when a ship is present at the market.
	Transactions []MarketTransaction `json:"transactions,omitempty"`
}
