// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ScannedSystem struct {
	Distance     int64  `json:"distance"`
	SectorSymbol string `json:"sectorSymbol"`
	Symbol       string `json:"symbol"`
	// The type of waypoint.
	Type SystemType `json:"type"`
	X    int64      `json:"x"`
	Y    int64      `json:"y"`
}
