// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ScannedShipEngine - The engine of the ship.
type ScannedShipEngine struct {
	Symbol string `json:"symbol"`
}

// ScannedShipFrame - The frame of the ship.
type ScannedShipFrame struct {
	Symbol string `json:"symbol"`
}

// ScannedShipMounts - A mount on the ship.
type ScannedShipMounts struct {
	Symbol string `json:"symbol"`
}

// ScannedShipReactor - The reactor of the ship.
type ScannedShipReactor struct {
	Symbol string `json:"symbol"`
}

// ScannedShip - The ship that was scanned. Details include information about the ship that could be detected by the scanner.
type ScannedShip struct {
	// The engine of the ship.
	Engine ScannedShipEngine `json:"engine"`
	// The frame of the ship.
	Frame  *ScannedShipFrame   `json:"frame,omitempty"`
	Mounts []ScannedShipMounts `json:"mounts,omitempty"`
	// The navigation information of the ship.
	Nav ShipNav `json:"nav"`
	// The reactor of the ship.
	Reactor *ScannedShipReactor `json:"reactor,omitempty"`
	// The public registration information of the ship
	Registration ShipRegistration `json:"registration"`
	// The globally unique identifier of the ship.
	Symbol string `json:"symbol"`
}
