// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ShipCargo struct {
	// The max number of items that can be stored in the cargo hold.
	Capacity int64 `json:"capacity"`
	// The items currently in the cargo hold.
	Inventory []ShipCargoItem `json:"inventory"`
	// The number of items currently stored in the cargo hold.
	Units int64 `json:"units"`
}
