// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// ShipNavFlightMode - The ship's set speed when traveling between waypoints or systems.
type ShipNavFlightMode string

const (
	ShipNavFlightModeDrift   ShipNavFlightMode = "DRIFT"
	ShipNavFlightModeStealth ShipNavFlightMode = "STEALTH"
	ShipNavFlightModeCruise  ShipNavFlightMode = "CRUISE"
	ShipNavFlightModeBurn    ShipNavFlightMode = "BURN"
)

func (e ShipNavFlightMode) ToPointer() *ShipNavFlightMode {
	return &e
}

func (e *ShipNavFlightMode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "DRIFT":
		fallthrough
	case "STEALTH":
		fallthrough
	case "CRUISE":
		fallthrough
	case "BURN":
		*e = ShipNavFlightMode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ShipNavFlightMode: %v", v)
	}
}
