// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

type ShipyardTransaction struct {
	// The symbol of the agent that made the transaction.
	AgentSymbol string `json:"agentSymbol"`
	// The price of the transaction.
	Price int64 `json:"price"`
	// The symbol of the ship that was purchased.
	ShipSymbol string `json:"shipSymbol"`
	// The timestamp of the transaction.
	Timestamp time.Time `json:"timestamp"`
	// The symbol of the waypoint where the transaction took place.
	WaypointSymbol string `json:"waypointSymbol"`
}
