// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ShipNav - The navigation information of the ship.
type ShipNav struct {
	// The ship's set speed when traveling between waypoints or systems.
	FlightMode ShipNavFlightMode `json:"flightMode"`
	// The routing information for the ship's most recent transit or current location.
	Route ShipNavRoute `json:"route"`
	// The current status of the ship
	Status ShipNavStatus `json:"status"`
	// The system symbol of the ship's current location.
	SystemSymbol string `json:"systemSymbol"`
	// The waypoint symbol of the ship's current location, or if the ship is in-transit, the waypoint symbol of the ship's destination.
	WaypointSymbol string `json:"waypointSymbol"`
}
