// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ShipyardShip struct {
	Description string `json:"description"`
	// The engine determines how quickly a ship travels between waypoints.
	Engine ShipEngine `json:"engine"`
	// The frame of the ship. The frame determines the number of modules and mounting points of the ship, as well as base fuel capacity. As the condition of the frame takes more wear, the ship will become more sluggish and less maneuverable.
	Frame         ShipFrame    `json:"frame"`
	Modules       []ShipModule `json:"modules"`
	Mounts        []ShipMount  `json:"mounts"`
	Name          string       `json:"name"`
	PurchasePrice int64        `json:"purchasePrice"`
	// The reactor of the ship. The reactor is responsible for powering the ship's systems and weapons.
	Reactor ShipReactor `json:"reactor"`
	Type    *ShipType   `json:"type,omitempty"`
}
