// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// ShipCrewRotation - The rotation of crew shifts. A stricter shift improves the ship's performance. A more relaxed shift improves the crew's morale.
type ShipCrewRotation string

const (
	ShipCrewRotationStrict  ShipCrewRotation = "STRICT"
	ShipCrewRotationRelaxed ShipCrewRotation = "RELAXED"
)

func (e ShipCrewRotation) ToPointer() *ShipCrewRotation {
	return &e
}

func (e *ShipCrewRotation) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "STRICT":
		fallthrough
	case "RELAXED":
		*e = ShipCrewRotation(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ShipCrewRotation: %v", v)
	}
}

// ShipCrew - The ship's crew service and maintain the ship's systems and equipment.
type ShipCrew struct {
	// The maximum number of crew members the ship can support.
	Capacity int64 `json:"capacity"`
	// The current number of crew members on the ship.
	Current int64 `json:"current"`
	// A rough measure of the crew's morale. A higher morale means the crew is happier and more productive. A lower morale means the ship is more prone to accidents.
	Morale int64 `json:"morale"`
	// The minimum number of crew members required to maintain the ship.
	Required int64 `json:"required"`
	// The rotation of crew shifts. A stricter shift improves the ship's performance. A more relaxed shift improves the crew's morale.
	Rotation ShipCrewRotation `json:"rotation"`
	// The amount of credits per crew member paid per hour. Wages are paid when a ship docks at a civilized waypoint.
	Wages int64 `json:"wages"`
}
