// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// ShipNavStatus - The current status of the ship
type ShipNavStatus string

const (
	ShipNavStatusInTransit ShipNavStatus = "IN_TRANSIT"
	ShipNavStatusInOrbit   ShipNavStatus = "IN_ORBIT"
	ShipNavStatusDocked    ShipNavStatus = "DOCKED"
)

func (e ShipNavStatus) ToPointer() *ShipNavStatus {
	return &e
}

func (e *ShipNavStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "IN_TRANSIT":
		fallthrough
	case "IN_ORBIT":
		fallthrough
	case "DOCKED":
		*e = ShipNavStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ShipNavStatus: %v", v)
	}
}
