// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ShipyardShipTypes struct {
	Type *ShipType `json:"type,omitempty"`
}

type Shipyard struct {
	// The list of ship types available for purchase at this shipyard.
	ShipTypes []ShipyardShipTypes `json:"shipTypes"`
	// The ships that are currently available for purchase at the shipyard.
	Ships []ShipyardShip `json:"ships,omitempty"`
	// The symbol of the shipyard. The symbol is the same as the waypoint where the shipyard is located.
	Symbol string `json:"symbol"`
	// The list of recent transactions at this shipyard.
	Transactions []ShipyardTransaction `json:"transactions,omitempty"`
}
