// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ShipCargoItem - The type of cargo item and the number of units.
type ShipCargoItem struct {
	// The description of the cargo item type.
	Description string `json:"description"`
	// The name of the cargo item type.
	Name string `json:"name"`
	// The unique identifier of the cargo item type.
	Symbol string `json:"symbol"`
	// The number of units of the cargo item.
	Units int64 `json:"units"`
}
