// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

type ShipFuelConsumed struct {
	// The amount of fuel consumed by the most recent transit or action.
	Amount int64 `json:"amount"`
	// The time at which the fuel was consumed.
	Timestamp time.Time `json:"timestamp"`
}

// ShipFuel - Details of the ship's fuel tanks including how much fuel was consumed during the last transit or action.
type ShipFuel struct {
	// The maximum amount of fuel the ship's tanks can hold.
	Capacity int64             `json:"capacity"`
	Consumed *ShipFuelConsumed `json:"consumed,omitempty"`
	// The current amount of fuel in the ship's tanks.
	Current int64 `json:"current"`
}
