// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

// ShipNavRoute - The routing information for the ship's most recent transit or current location.
type ShipNavRoute struct {
	// The date time of the ship's arrival. If the ship is in-transit, this is the expected time of arrival.
	Arrival time.Time `json:"arrival"`
	// The destination or departure of a ships nav route.
	Departure ShipNavRouteWaypoint `json:"departure"`
	// The date time of the ship's departure.
	DepartureTime time.Time `json:"departureTime"`
	// The destination or departure of a ships nav route.
	Destination ShipNavRouteWaypoint `json:"destination"`
}
