// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ShipRegistration - The public registration information of the ship
type ShipRegistration struct {
	// The symbol of the faction the ship is registered with
	FactionSymbol string `json:"factionSymbol"`
	// The agent's registered name of the ship
	Name string `json:"name"`
	// The registered role of the ship
	Role ShipRole `json:"role"`
}
