// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ShipNavRouteWaypoint - The destination or departure of a ships nav route.
type ShipNavRouteWaypoint struct {
	Symbol       string `json:"symbol"`
	SystemSymbol string `json:"systemSymbol"`
	// The type of waypoint.
	Type WaypointType `json:"type"`
	X    int64        `json:"x"`
	Y    int64        `json:"y"`
}
