// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// SurveyDeposit - A surveyed deposit of a mineral or resource available for extraction.
type SurveyDeposit struct {
	// The symbol of the deposit.
	Symbol string `json:"symbol"`
}
