// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type SystemWaypoint struct {
	Symbol string `json:"symbol"`
	// The type of waypoint.
	Type WaypointType `json:"type"`
	X    int64        `json:"x"`
	Y    int64        `json:"y"`
}
