// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type System struct {
	Factions     []SystemFaction `json:"factions"`
	SectorSymbol string          `json:"sectorSymbol"`
	Symbol       string          `json:"symbol"`
	// The type of waypoint.
	Type      SystemType       `json:"type"`
	Waypoints []SystemWaypoint `json:"waypoints"`
	X         int64            `json:"x"`
	Y         int64            `json:"y"`
}
