// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type TradeSymbol string

const (
	TradeSymbolPreciousStones          TradeSymbol = "PRECIOUS_STONES"
	TradeSymbolQuartzSand              TradeSymbol = "QUARTZ_SAND"
	TradeSymbolSiliconCrystals         TradeSymbol = "SILICON_CRYSTALS"
	TradeSymbolAmmoniaIce              TradeSymbol = "AMMONIA_ICE"
	TradeSymbolLiquidHydrogen          TradeSymbol = "LIQUID_HYDROGEN"
	TradeSymbolLiquidNitrogen          TradeSymbol = "LIQUID_NITROGEN"
	TradeSymbolIceWater                TradeSymbol = "ICE_WATER"
	TradeSymbolExoticMatter            TradeSymbol = "EXOTIC_MATTER"
	TradeSymbolAdvancedCircuitry       TradeSymbol = "ADVANCED_CIRCUITRY"
	TradeSymbolGravitonEmitters        TradeSymbol = "GRAVITON_EMITTERS"
	TradeSymbolIron                    TradeSymbol = "IRON"
	TradeSymbolIronOre                 TradeSymbol = "IRON_ORE"
	TradeSymbolCopper                  TradeSymbol = "COPPER"
	TradeSymbolCopperOre               TradeSymbol = "COPPER_ORE"
	TradeSymbolAluminum                TradeSymbol = "ALUMINUM"
	TradeSymbolAluminumOre             TradeSymbol = "ALUMINUM_ORE"
	TradeSymbolSilver                  TradeSymbol = "SILVER"
	TradeSymbolSilverOre               TradeSymbol = "SILVER_ORE"
	TradeSymbolGold                    TradeSymbol = "GOLD"
	TradeSymbolGoldOre                 TradeSymbol = "GOLD_ORE"
	TradeSymbolPlatinum                TradeSymbol = "PLATINUM"
	TradeSymbolPlatinumOre             TradeSymbol = "PLATINUM_ORE"
	TradeSymbolDiamonds                TradeSymbol = "DIAMONDS"
	TradeSymbolUranite                 TradeSymbol = "URANITE"
	TradeSymbolUraniteOre              TradeSymbol = "URANITE_ORE"
	TradeSymbolMeritium                TradeSymbol = "MERITIUM"
	TradeSymbolMeritiumOre             TradeSymbol = "MERITIUM_ORE"
	TradeSymbolHydrocarbon             TradeSymbol = "HYDROCARBON"
	TradeSymbolAntimatter              TradeSymbol = "ANTIMATTER"
	TradeSymbolFertilizers             TradeSymbol = "FERTILIZERS"
	TradeSymbolFabrics                 TradeSymbol = "FABRICS"
	TradeSymbolFood                    TradeSymbol = "FOOD"
	TradeSymbolJewelry                 TradeSymbol = "JEWELRY"
	TradeSymbolMachinery               TradeSymbol = "MACHINERY"
	TradeSymbolFirearms                TradeSymbol = "FIREARMS"
	TradeSymbolAssaultRifles           TradeSymbol = "ASSAULT_RIFLES"
	TradeSymbolMilitaryEquipment       TradeSymbol = "MILITARY_EQUIPMENT"
	TradeSymbolExplosives              TradeSymbol = "EXPLOSIVES"
	TradeSymbolLabInstruments          TradeSymbol = "LAB_INSTRUMENTS"
	TradeSymbolAmmunition              TradeSymbol = "AMMUNITION"
	TradeSymbolElectronics             TradeSymbol = "ELECTRONICS"
	TradeSymbolShipPlating             TradeSymbol = "SHIP_PLATING"
	TradeSymbolEquipment               TradeSymbol = "EQUIPMENT"
	TradeSymbolFuel                    TradeSymbol = "FUEL"
	TradeSymbolMedicine                TradeSymbol = "MEDICINE"
	TradeSymbolDrugs                   TradeSymbol = "DRUGS"
	TradeSymbolClothing                TradeSymbol = "CLOTHING"
	TradeSymbolMicroprocessors         TradeSymbol = "MICROPROCESSORS"
	TradeSymbolPlastics                TradeSymbol = "PLASTICS"
	TradeSymbolPolynucleotides         TradeSymbol = "POLYNUCLEOTIDES"
	TradeSymbolBiocomposites           TradeSymbol = "BIOCOMPOSITES"
	TradeSymbolNanobots                TradeSymbol = "NANOBOTS"
	TradeSymbolAiMainframes            TradeSymbol = "AI_MAINFRAMES"
	TradeSymbolQuantumDrives           TradeSymbol = "QUANTUM_DRIVES"
	TradeSymbolRoboticDrones           TradeSymbol = "ROBOTIC_DRONES"
	TradeSymbolCyberImplants           TradeSymbol = "CYBER_IMPLANTS"
	TradeSymbolGeneTherapeutics        TradeSymbol = "GENE_THERAPEUTICS"
	TradeSymbolNeuralChips             TradeSymbol = "NEURAL_CHIPS"
	TradeSymbolMoodRegulators          TradeSymbol = "MOOD_REGULATORS"
	TradeSymbolViralAgents             TradeSymbol = "VIRAL_AGENTS"
	TradeSymbolMicroFusionGenerators   TradeSymbol = "MICRO_FUSION_GENERATORS"
	TradeSymbolSupergrains             TradeSymbol = "SUPERGRAINS"
	TradeSymbolLaserRifles             TradeSymbol = "LASER_RIFLES"
	TradeSymbolHolographics            TradeSymbol = "HOLOGRAPHICS"
	TradeSymbolShipSalvage             TradeSymbol = "SHIP_SALVAGE"
	TradeSymbolRelicTech               TradeSymbol = "RELIC_TECH"
	TradeSymbolNovelLifeforms          TradeSymbol = "NOVEL_LIFEFORMS"
	TradeSymbolBotanicalSpecimens      TradeSymbol = "BOTANICAL_SPECIMENS"
	TradeSymbolCulturalArtifacts       TradeSymbol = "CULTURAL_ARTIFACTS"
	TradeSymbolReactorSolarI           TradeSymbol = "REACTOR_SOLAR_I"
	TradeSymbolReactorFusionI          TradeSymbol = "REACTOR_FUSION_I"
	TradeSymbolReactorFissionI         TradeSymbol = "REACTOR_FISSION_I"
	TradeSymbolReactorChemicalI        TradeSymbol = "REACTOR_CHEMICAL_I"
	TradeSymbolReactorAntimatterI      TradeSymbol = "REACTOR_ANTIMATTER_I"
	TradeSymbolEngineImpulseDriveI     TradeSymbol = "ENGINE_IMPULSE_DRIVE_I"
	TradeSymbolEngineIonDriveI         TradeSymbol = "ENGINE_ION_DRIVE_I"
	TradeSymbolEngineIonDriveIi        TradeSymbol = "ENGINE_ION_DRIVE_II"
	TradeSymbolEngineHyperDriveI       TradeSymbol = "ENGINE_HYPER_DRIVE_I"
	TradeSymbolModuleMineralProcessorI TradeSymbol = "MODULE_MINERAL_PROCESSOR_I"
	TradeSymbolModuleCargoHoldI        TradeSymbol = "MODULE_CARGO_HOLD_I"
	TradeSymbolModuleCrewQuartersI     TradeSymbol = "MODULE_CREW_QUARTERS_I"
	TradeSymbolModuleEnvoyQuartersI    TradeSymbol = "MODULE_ENVOY_QUARTERS_I"
	TradeSymbolModulePassengerCabinI   TradeSymbol = "MODULE_PASSENGER_CABIN_I"
	TradeSymbolModuleMicroRefineryI    TradeSymbol = "MODULE_MICRO_REFINERY_I"
	TradeSymbolModuleOreRefineryI      TradeSymbol = "MODULE_ORE_REFINERY_I"
	TradeSymbolModuleFuelRefineryI     TradeSymbol = "MODULE_FUEL_REFINERY_I"
	TradeSymbolModuleScienceLabI       TradeSymbol = "MODULE_SCIENCE_LAB_I"
	TradeSymbolModuleJumpDriveI        TradeSymbol = "MODULE_JUMP_DRIVE_I"
	TradeSymbolModuleJumpDriveIi       TradeSymbol = "MODULE_JUMP_DRIVE_II"
	TradeSymbolModuleJumpDriveIii      TradeSymbol = "MODULE_JUMP_DRIVE_III"
	TradeSymbolModuleWarpDriveI        TradeSymbol = "MODULE_WARP_DRIVE_I"
	TradeSymbolModuleWarpDriveIi       TradeSymbol = "MODULE_WARP_DRIVE_II"
	TradeSymbolModuleWarpDriveIii      TradeSymbol = "MODULE_WARP_DRIVE_III"
	TradeSymbolModuleShieldGeneratorI  TradeSymbol = "MODULE_SHIELD_GENERATOR_I"
	TradeSymbolModuleShieldGeneratorIi TradeSymbol = "MODULE_SHIELD_GENERATOR_II"
	TradeSymbolMountGasSiphonI         TradeSymbol = "MOUNT_GAS_SIPHON_I"
	TradeSymbolMountGasSiphonIi        TradeSymbol = "MOUNT_GAS_SIPHON_II"
	TradeSymbolMountGasSiphonIii       TradeSymbol = "MOUNT_GAS_SIPHON_III"
	TradeSymbolMountSurveyorI          TradeSymbol = "MOUNT_SURVEYOR_I"
	TradeSymbolMountSurveyorIi         TradeSymbol = "MOUNT_SURVEYOR_II"
	TradeSymbolMountSurveyorIii        TradeSymbol = "MOUNT_SURVEYOR_III"
	TradeSymbolMountSensorArrayI       TradeSymbol = "MOUNT_SENSOR_ARRAY_I"
	TradeSymbolMountSensorArrayIi      TradeSymbol = "MOUNT_SENSOR_ARRAY_II"
	TradeSymbolMountSensorArrayIii     TradeSymbol = "MOUNT_SENSOR_ARRAY_III"
	TradeSymbolMountMiningLaserI       TradeSymbol = "MOUNT_MINING_LASER_I"
	TradeSymbolMountMiningLaserIi      TradeSymbol = "MOUNT_MINING_LASER_II"
	TradeSymbolMountMiningLaserIii     TradeSymbol = "MOUNT_MINING_LASER_III"
	TradeSymbolMountLaserCannonI       TradeSymbol = "MOUNT_LASER_CANNON_I"
	TradeSymbolMountMissileLauncherI   TradeSymbol = "MOUNT_MISSILE_LAUNCHER_I"
	TradeSymbolMountTurretI            TradeSymbol = "MOUNT_TURRET_I"
)

func (e TradeSymbol) ToPointer() *TradeSymbol {
	return &e
}

func (e *TradeSymbol) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "PRECIOUS_STONES":
		fallthrough
	case "QUARTZ_SAND":
		fallthrough
	case "SILICON_CRYSTALS":
		fallthrough
	case "AMMONIA_ICE":
		fallthrough
	case "LIQUID_HYDROGEN":
		fallthrough
	case "LIQUID_NITROGEN":
		fallthrough
	case "ICE_WATER":
		fallthrough
	case "EXOTIC_MATTER":
		fallthrough
	case "ADVANCED_CIRCUITRY":
		fallthrough
	case "GRAVITON_EMITTERS":
		fallthrough
	case "IRON":
		fallthrough
	case "IRON_ORE":
		fallthrough
	case "COPPER":
		fallthrough
	case "COPPER_ORE":
		fallthrough
	case "ALUMINUM":
		fallthrough
	case "ALUMINUM_ORE":
		fallthrough
	case "SILVER":
		fallthrough
	case "SILVER_ORE":
		fallthrough
	case "GOLD":
		fallthrough
	case "GOLD_ORE":
		fallthrough
	case "PLATINUM":
		fallthrough
	case "PLATINUM_ORE":
		fallthrough
	case "DIAMONDS":
		fallthrough
	case "URANITE":
		fallthrough
	case "URANITE_ORE":
		fallthrough
	case "MERITIUM":
		fallthrough
	case "MERITIUM_ORE":
		fallthrough
	case "HYDROCARBON":
		fallthrough
	case "ANTIMATTER":
		fallthrough
	case "FERTILIZERS":
		fallthrough
	case "FABRICS":
		fallthrough
	case "FOOD":
		fallthrough
	case "JEWELRY":
		fallthrough
	case "MACHINERY":
		fallthrough
	case "FIREARMS":
		fallthrough
	case "ASSAULT_RIFLES":
		fallthrough
	case "MILITARY_EQUIPMENT":
		fallthrough
	case "EXPLOSIVES":
		fallthrough
	case "LAB_INSTRUMENTS":
		fallthrough
	case "AMMUNITION":
		fallthrough
	case "ELECTRONICS":
		fallthrough
	case "SHIP_PLATING":
		fallthrough
	case "EQUIPMENT":
		fallthrough
	case "FUEL":
		fallthrough
	case "MEDICINE":
		fallthrough
	case "DRUGS":
		fallthrough
	case "CLOTHING":
		fallthrough
	case "MICROPROCESSORS":
		fallthrough
	case "PLASTICS":
		fallthrough
	case "POLYNUCLEOTIDES":
		fallthrough
	case "BIOCOMPOSITES":
		fallthrough
	case "NANOBOTS":
		fallthrough
	case "AI_MAINFRAMES":
		fallthrough
	case "QUANTUM_DRIVES":
		fallthrough
	case "ROBOTIC_DRONES":
		fallthrough
	case "CYBER_IMPLANTS":
		fallthrough
	case "GENE_THERAPEUTICS":
		fallthrough
	case "NEURAL_CHIPS":
		fallthrough
	case "MOOD_REGULATORS":
		fallthrough
	case "VIRAL_AGENTS":
		fallthrough
	case "MICRO_FUSION_GENERATORS":
		fallthrough
	case "SUPERGRAINS":
		fallthrough
	case "LASER_RIFLES":
		fallthrough
	case "HOLOGRAPHICS":
		fallthrough
	case "SHIP_SALVAGE":
		fallthrough
	case "RELIC_TECH":
		fallthrough
	case "NOVEL_LIFEFORMS":
		fallthrough
	case "BOTANICAL_SPECIMENS":
		fallthrough
	case "CULTURAL_ARTIFACTS":
		fallthrough
	case "REACTOR_SOLAR_I":
		fallthrough
	case "REACTOR_FUSION_I":
		fallthrough
	case "REACTOR_FISSION_I":
		fallthrough
	case "REACTOR_CHEMICAL_I":
		fallthrough
	case "REACTOR_ANTIMATTER_I":
		fallthrough
	case "ENGINE_IMPULSE_DRIVE_I":
		fallthrough
	case "ENGINE_ION_DRIVE_I":
		fallthrough
	case "ENGINE_ION_DRIVE_II":
		fallthrough
	case "ENGINE_HYPER_DRIVE_I":
		fallthrough
	case "MODULE_MINERAL_PROCESSOR_I":
		fallthrough
	case "MODULE_CARGO_HOLD_I":
		fallthrough
	case "MODULE_CREW_QUARTERS_I":
		fallthrough
	case "MODULE_ENVOY_QUARTERS_I":
		fallthrough
	case "MODULE_PASSENGER_CABIN_I":
		fallthrough
	case "MODULE_MICRO_REFINERY_I":
		fallthrough
	case "MODULE_ORE_REFINERY_I":
		fallthrough
	case "MODULE_FUEL_REFINERY_I":
		fallthrough
	case "MODULE_SCIENCE_LAB_I":
		fallthrough
	case "MODULE_JUMP_DRIVE_I":
		fallthrough
	case "MODULE_JUMP_DRIVE_II":
		fallthrough
	case "MODULE_JUMP_DRIVE_III":
		fallthrough
	case "MODULE_WARP_DRIVE_I":
		fallthrough
	case "MODULE_WARP_DRIVE_II":
		fallthrough
	case "MODULE_WARP_DRIVE_III":
		fallthrough
	case "MODULE_SHIELD_GENERATOR_I":
		fallthrough
	case "MODULE_SHIELD_GENERATOR_II":
		fallthrough
	case "MOUNT_GAS_SIPHON_I":
		fallthrough
	case "MOUNT_GAS_SIPHON_II":
		fallthrough
	case "MOUNT_GAS_SIPHON_III":
		fallthrough
	case "MOUNT_SURVEYOR_I":
		fallthrough
	case "MOUNT_SURVEYOR_II":
		fallthrough
	case "MOUNT_SURVEYOR_III":
		fallthrough
	case "MOUNT_SENSOR_ARRAY_I":
		fallthrough
	case "MOUNT_SENSOR_ARRAY_II":
		fallthrough
	case "MOUNT_SENSOR_ARRAY_III":
		fallthrough
	case "MOUNT_MINING_LASER_I":
		fallthrough
	case "MOUNT_MINING_LASER_II":
		fallthrough
	case "MOUNT_MINING_LASER_III":
		fallthrough
	case "MOUNT_LASER_CANNON_I":
		fallthrough
	case "MOUNT_MISSILE_LAUNCHER_I":
		fallthrough
	case "MOUNT_TURRET_I":
		*e = TradeSymbol(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TradeSymbol: %v", v)
	}
}
