// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type TradeGood struct {
	Description string      `json:"description"`
	Name        string      `json:"name"`
	Symbol      TradeSymbol `json:"symbol"`
}
