// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// WaypointType - The type of waypoint.
type WaypointType string

const (
	WaypointTypePlanet         WaypointType = "PLANET"
	WaypointTypeGasGiant       WaypointType = "GAS_GIANT"
	WaypointTypeMoon           WaypointType = "MOON"
	WaypointTypeOrbitalStation WaypointType = "ORBITAL_STATION"
	WaypointTypeJumpGate       WaypointType = "JUMP_GATE"
	WaypointTypeAsteroidField  WaypointType = "ASTEROID_FIELD"
	WaypointTypeNebula         WaypointType = "NEBULA"
	WaypointTypeDebrisField    WaypointType = "DEBRIS_FIELD"
	WaypointTypeGravityWell    WaypointType = "GRAVITY_WELL"
)

func (e WaypointType) ToPointer() *WaypointType {
	return &e
}

func (e *WaypointType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "PLANET":
		fallthrough
	case "GAS_GIANT":
		fallthrough
	case "MOON":
		fallthrough
	case "ORBITAL_STATION":
		fallthrough
	case "JUMP_GATE":
		fallthrough
	case "ASTEROID_FIELD":
		fallthrough
	case "NEBULA":
		fallthrough
	case "DEBRIS_FIELD":
		fallthrough
	case "GRAVITY_WELL":
		*e = WaypointType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for WaypointType: %v", v)
	}
}
