// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// WaypointOrbital - An orbital is another waypoint that orbits a parent waypoint.
type WaypointOrbital struct {
	Symbol string `json:"symbol"`
}
